# Generated by Django 6.0.2 on 2026-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='train',
            name='coach_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Sleeper', 'Sleeper'), ('General', 'General')], default='AC', max_length=20),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
