# Generated by Django 6.0.2 on 2026-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_booking_booked_on_train_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_number',
            field=models.CharField(default='TEMP123', max_length=20),
        ),
    ]
